In [20]:
import pandas as pd

# wikipediaから各表を取得し、テーブル要素数を取得
url = "https://ja.wikipedia.org/wiki/%E3%83%88%E3%83%83%E3%83%97%E3%83%AC%E3%83%99%E3%83%AB%E3%83%89%E3%83%A1%E3%82%A4%E3%83%B3%E4%B8%80%E8%A6%A7#%E5%9B%BD%E5%88%A5%E3%82%B3%E3%83%BC%E3%83%89%E3%83%88%E3%83%83%E3%83%97%E3%83%AC%E3%83%99%E3%83%AB%E3%83%89%E3%83%A1%E3%82%A4%E3%83%B3"
tables = pd.read_html(url)
len(tables)

43

In [25]:
# 5番目の表を取得（国別コードトップレベルドメイン表）
df = tables[4]
df

,Name,Entity,Explanation,Notes,IDN,DNSSEC,SLD,IPv6
0,.ac,アセンション島,NaN,広く学術的なサイト（大学など）のために用いられる。アセンション島はイギリス領であるが、イギリ...,Yes,Yes,Yes,Yes
1,.ad,アンドラ,NaN,アンドラにおける商標または市民権が必要となる[7][8]。,NaN,Yes,Yes,NaN
2,.ae,アラブ首長国連邦,NaN,NaN,NaN,No,Yes,NaN
3,.af,アフガニスタン,NaN,NaN,NaN,Yes,Yes,NaN
4,.ag,アンティグア・バーブーダ,NaN,AGがドイツの株式会社(Aktiengesellschaft)の略称であることから、非公式に...,NaN,Yes,Yes,NaN
...,...,...,...,...,...,...,...,...
248,.ye,イエメン,NaN,NaN,NaN,No,No,NaN
249,.yt,マヨット島,NaN,欧州連合・スイス・ノルウェー・アイスランド・リヒテンシュタインの個人・企業に限る[cctld...,Yes[cctld 12],Yes,Yes,NaN
250,.za,南アフリカ,Zuid-Afrika (オランダ語),NaN,NaN,No,No,NaN
251,.zm,ザンビア,NaN,NaN,NaN,Yes,Yes[cctld 28],NaN
252,.zw,ジンバブエ,NaN,NaN,NaN,No,No,NaN

In [28]:
# csvファイルに書き出す
df.to_csv("write_data.csv")